### ISSUE TITLE
Deprecated Form Uploads

### ISSUE THREAD

**Issue by pivnicek** [keboola/sapi-r-client#4]
Sapi has deprecated form uploads, so the save table needs to be forced to use the async/federated token

**Comment by MiroCillik** [comment]
https://github.com/keboola/connection/issues/1448

**Comment by pivnicek** [comment]
```
Warning: Error in value[[3L]]: error preparing file upload Error in .self$decodeResponse(httr::POST(paste0(.self$url, "storage/files/prepare"), : Error recieving response from sapi API: Form upload is deprecated. Please use federationToken parameter for upload.400Error recieving response from sapi API: keboola-connection-087229cd6b4e6f36fd91bde7b1bca5e2400
```

**Comment by pivnicek** [comment]
Need to add federationToken option here: https://github.com/keboola/sapi-r-client/blob/master/R/client.R#L265

**Comment by pivnicek** [comment]
Uf, won't be so simple.  Will need to either implement raw S3 multi-part updload request, or add a dependency to an R s3 client (probably https://github.com/cloudyr/aws.s3 - we're already using the signature generator from them).

**Comment by odinuv** [comment]
y, we should use the cloudyr s3 client if it works (Afaik it does)

**Comment by pivnicek** [comment]
yeah, it looks solid and active.  ok, that will kill the necessity for the low-level `s3GET` method we have here too.  I'll try it out.

**Comment by pivnicek** [comment]
I guess we can just `set-env` the credentials every time and then unset them in a `finally` block.
